const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("contextPromptAssistant", {
  resolveTarget: (url) => ipcRenderer.invoke("resolve-target", url),
  refreshContext: (payload) => ipcRenderer.invoke("refresh-context", payload),
  optimize: (payload) => ipcRenderer.invoke("optimize", payload),
  cancelOptimize: (requestId) => ipcRenderer.invoke("cancel-optimize", requestId),
  copy: (text) => ipcRenderer.invoke("copy", text),
  readClipboard: () => ipcRenderer.invoke("read-clipboard"),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke("set-always-on-top", enabled),
  getPreferences: () => ipcRenderer.invoke("get-preferences"),
  setLayout: (layout) => ipcRenderer.invoke("set-layout", layout),
  setFontScale: (fontScale) => ipcRenderer.invoke("set-font-scale", fontScale),
  setAutoShow: (enabled) => ipcRenderer.invoke("set-auto-show", enabled),
  getDiagnostics: () => ipcRenderer.invoke("get-diagnostics"),
  chooseCodexExecutable: () => ipcRenderer.invoke("choose-codex-executable"),
  launchCodex: () => ipcRenderer.invoke("launch-codex"),
  showWindow: () => ipcRenderer.invoke("show-window"),
  hideWindow: () => ipcRenderer.invoke("hide-window"),
  quit: () => ipcRenderer.invoke("quit"),
  openLink: (url) => ipcRenderer.invoke("open-link", url),
  onPreferences: (callback) => ipcRenderer.on("preferences", (_event, value) => callback(value)),
  onCodexStatus: (callback) => ipcRenderer.on("codex-status", (_event, value) => callback(value)),
  onDiagnostics: (callback) => ipcRenderer.on("diagnostics", (_event, value) => callback(value)),
  onDiagnosticMessage: (callback) => ipcRenderer.on("diagnostic-message", (_event, value) => callback(value)),
  onOpenSettings: (callback) => ipcRenderer.on("open-settings", () => callback()),
});
